// Content loading. Everything under data/ is generated by tools/build.py; never edit it by hand.

let manifest = null;
const categoryCache = {};
let toolkitCache = null;
let searchCache = null;
const examCache = {};
const itemIdCache = {};

const RANDOM_EXAM = { id: 'random', title: 'Random practice exam', minutes: 180, passPercent: 70, count: 100 };
const EXAM_PER_DOMAIN = 20;

async function fetchJson(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Could not load ${url} (${res.status})`);
  return res.json();
}

async function loadManifest() {
  if (!manifest) manifest = await fetchJson('data/manifest.json');
  return manifest;
}

async function loadCategory(cid) {
  if (!categoryCache[cid]) categoryCache[cid] = await fetchJson(`data/cat-${cid}.json`);
  return categoryCache[cid];
}

async function loadToolkit() {
  if (!toolkitCache) toolkitCache = await fetchJson('data/toolkit.json');
  return toolkitCache;
}

async function loadExam(id) {
  if (!examCache[id]) examCache[id] = await fetchJson(`data/exams/${id}.json`);
  return examCache[id];
}

// Rows of [focus id, title, outline text, guide body], plain text.
async function loadSearchIndex() {
  if (!searchCache) searchCache = await fetchJson('data/search.json');
  return searchCache;
}

function domainIds() {
  return Object.keys(manifest.domains).sort();
}

function categoryIds() {
  return domainIds().flatMap((d) => manifest.domains[d].categories);
}

// Scope IDs share one hierarchy: "all", domain "3", category "3.4", topic "3.4.1".
function focusIdsIn(scope) {
  if (scope === 'all') return Object.keys(manifest.focus);
  const depth = scope.split('.').length;
  if (depth === 1) return manifest.domains[scope].categories.flatMap(focusIdsIn);
  if (depth === 2) return manifest.categories[scope].topics.flatMap(focusIdsIn);
  return manifest.topics[scope].focus;
}

function scopeTitle(scope) {
  if (scope === 'all') return 'Overall';
  const depth = scope.split('.').length;
  if (depth === 1) return manifest.domains[scope].title;
  if (depth === 2) return manifest.categories[scope].title;
  return manifest.topics[scope].title;
}

function neighborCategory(cid, step) {
  const ids = categoryIds();
  return ids[ids.indexOf(cid) + step] || null;
}

function byNaturalId(a, b) {
  return a.localeCompare(b, undefined, { numeric: true });
}

// kind is 'q' (questions) or 'p' (workbook problems). Every item tests at least one focus point,
// so the union of the focus-point lists is the full set.
function allItemIds(kind) {
  if (!itemIdCache[kind]) {
    const ids = new Set(Object.values(manifest.focus).flatMap((f) => f[kind]));
    itemIdCache[kind] = [...ids].sort(byNaturalId);
  }
  return itemIdCache[kind];
}

// Items grouped by the topic they are filed under (the part of the ID before the dash).
function itemIdsIn(kind, scope) {
  if (scope === 'all') return allItemIds(kind);
  return allItemIds(kind).filter((id) => `${id.split('-')[0]}.`.startsWith(`${scope}.`));
}

function shuffled(list) {
  const out = [...list];
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

// 20 questions per domain from the practice pool, grouped by domain like the fixed exams.
function randomExamIds() {
  return domainIds().flatMap((d) => shuffled(itemIdsIn('q', d)).slice(0, EXAM_PER_DOMAIN));
}

function examDefs() {
  return [...manifest.exams, RANDOM_EXAM];
}

// An item can test a focus point in another category, so load every chunk the list touches.
async function loadItems(kind, ids) {
  const field = kind === 'q' ? 'questions' : 'problems';
  const cats = [...new Set(ids.map((id) => id.slice(0, 3)))];
  await Promise.all(cats.map(loadCategory));
  return ids.map((id) => categoryCache[id.slice(0, 3)][field][id]);
}
