// Offline support. Everything the app needs is cached on install and served cache-first.
// A new version installs in the background and waits until the reader taps "Reload",
// so the page never changes underneath someone mid-question.

// BUILD:START generated by tools/build.py; do not edit by hand
const VERSION = 'c79babdf6c87';
const PRECACHE = [
  "css/app.css",
  "css/tokens.css",
  "data/cat-1.1.json",
  "data/cat-1.2.json",
  "data/cat-1.3.json",
  "data/cat-1.4.json",
  "data/cat-2.1.json",
  "data/cat-2.2.json",
  "data/cat-2.3.json",
  "data/cat-2.4.json",
  "data/cat-3.1.json",
  "data/cat-3.2.json",
  "data/cat-3.3.json",
  "data/cat-3.4.json",
  "data/cat-3.5.json",
  "data/cat-4.1.json",
  "data/cat-4.2.json",
  "data/cat-5.1.json",
  "data/cat-5.2.json",
  "data/cat-5.3.json",
  "data/exams/EX-1.json",
  "data/exams/EX-2.json",
  "data/manifest.json",
  "data/search.json",
  "data/toolkit.json",
  "fonts/barlow-400.woff2",
  "fonts/barlow-500.woff2",
  "fonts/barlow-600.woff2",
  "fonts/barlow-700.woff2",
  "fonts/source-serif-greek.woff2",
  "fonts/source-serif-italic-greek.woff2",
  "fonts/source-serif-italic-latin.woff2",
  "fonts/source-serif-latin.woff2",
  "icons/apple-touch-icon.png",
  "icons/favicon-32.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "index.html",
  "js/app.js",
  "js/data.js",
  "js/state.js",
  "manifest.webmanifest"
];
// BUILD:END

const CACHE = `gb-study-${VERSION}`;

self.addEventListener('install', (event) => {
  // cache: 'reload' skips the browser's HTTP cache so a new version never precaches stale files.
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE.map((url) => new Request(url, { cache: 'reload' })))));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('gb-study-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()));
});

self.addEventListener('message', (event) => {
  if (event.data === 'skip-waiting') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    event.respondWith(caches.match('index.html').then((hit) => hit || fetch(req)));
    return;
  }
  event.respondWith(caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req)));
});
